### ISSUE TITLE
Use shared-modules/libusb

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.groestlcoin.electrum-grs#2]
libusb has been added to https://github.com/flathub/shared-modules.

**Comment by gruve-p** [comment]
Currently our fork is based on 3.3.8 version of electrum. We will update our next release when Electrum 4.0.0 comes out of beta.

Electrum-GRS needs an additional build (compared with electrum 4.0.0) to support other architectures: `groestlcoin_hash`  as can be seen here: https://github.com/Groestlcoin/electrum-grs/blob/v4.0.0/contrib/requirements/requirements.txt

Current electrum-grs 3.3.8 supports  `groestlcoin_hash` with: https://github.com/flathub/org.groestlcoin.electrum-grs/blob/master/groestlcoin-hash.json (which was generated through https://pypi.org/project/groestlcoin-hash/#files)

**Comment by A6GibKm** [comment]
I have a PR for electrum with all the required packages for 4.0.0b1  at https://github.com/flathub/org.electrum.electrum/pull/13. There might be something you find useful. Alternatively you can use `flatpak-pip-generator` from https://github.com/flatpak/flatpak-builder-tools to get pypi deps.

**Comment by gruve-p** [comment]
Thank you, the whole PR can be copied for Electrum-GRS. We just need to add `groestlcoin_hash` as extra dependency when Electrum comes out of beta through https://github.com/flatpak/flatpak-builder-tools/tree/master/pip

**Comment by gruve-p** [comment]
@A6GibKm We will try to update to v4.0.7 in https://github.com/flathub/org.groestlcoin.electrum-grs/pull/3 and close this issue
