### ISSUE TITLE
Fix translations in metainfo

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.groestlcoin.electrum-grs#8]
```xml
<translation></translation>
```

In the translations is wrong, see https://github.com/flathub/org.electrum.electrum/pull/34/commits/ee0e535d5941d7968223e2d5848810e9db0ede88 which has a link to the source with the correct name for the module.

**Comment by gruve-p** [comment]
Thanks for the report, will be fixed in electrum-grs 4.2.0 branch

**Comment by gruve-p** [comment]
Fixed in the [4.2.0](https://github.com/flathub/org.groestlcoin.electrum-grs/tree/4.2.0) branch
